model_name=cifar
save=0
suffix=update_1

sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_normal_${suffix}.pt --trained_file_suffix ${suffix} --beta 1 --save ${save} --evaluate_mode normal > experimental_results_new_10/${model_name}_inference_exits_normal.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 1 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_1.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 1.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_1.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 2 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_2.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 2.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_2.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 3 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_3.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 3.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_3.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 4 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_4.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 4.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_4.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 5.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_5.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 6 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_6.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 6.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_6.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 7 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_7.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 7.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_7.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 8 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_8.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 8.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_8.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 9 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_9.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 9.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_9.5.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 10 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_10.txt
sudo python3 main_new.py --model_name ${model_name} --optimizer adam --train_mode exits --task evaluate --device cuda --pretrained_file models_new/${model_name}_train_exits_${suffix}.pt --trained_file_suffix ${suffix} --beta 10.5 --save ${save} > experimental_results_new_10/${model_name}_inference_exits_beta_10.5.txt